# Dependencies
markdown:	redcarpet
pygments:	true


disqus:
    username: conorpp

# Permalinks
permalink:	/blog/:title

# Setup
title:		Conor Patrick
tagline:	'blog'
description:	'Security, Privacy, and some hardware projects.'
url:		/

author:
  name:		''
  url:		https://google.com/+IanCamporezBrunelli
  email:    conorpp \at vt \dot edu

paginate:	5

# Custom vars
icon:		/assets/images/profile.jpg
cover:		/assets/images/hammock.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/_conorpp
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/conorpp
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/+ConorPatrickpp/
    desc:	Add me on google+

  - icon:	feed
    url:	/atom.xml
    desc:	Subscribe to my feed

  - icon:	key
    url:	/assets/gpgkey.txt
    desc:	GPG Key
 
  - icon:	portfolio
    url:	http://devpost.com/conorpp94
    desc:	Hackathon Projects
    
menu:
  - title:	Home
    url:	/
    
    #  - title:	About
    #url:	/about.html
    
copyright:
  author:	Conor Patrick
  url:		/
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
