# Dependencies
markdown: kramdown

highlighter: rouge

sass:
    sass_dir: assets/sass/_sass
    style: compressed

permalink: pretty

# compress html but not really worth it
#gems:
#  - octopress-minify-html
#
collections:
    archive:
        permalink: /:title
        output: true

disqus:
    username: conorpp


# Setup
title:		Conor Patrick
tagline:	'blog'
description:	'Security, Privacy, and some hardware projects.'
url:		https://conorpp.com/

lastthing: I started making a clock with levitating arms.
lastlink: /designing-a-clock-with-levitating-arms-part-1


permalink: /:title


braintree: https://braintree.conorpp.com

author:
  name:		'Conor Patrick'
  url:		https://conorpp.com
  email:    conorpp94 (at) gmail (dot) com

# paginate:	5

# Custom vars
icon:		/assets/images/profile.jpg
cover:		/assets/images/hammock.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/_conorpp
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/conorpp
    desc:	Fork me on github

    #  - icon:	googleplus-alt
    #url:	https://plus.google.com/+ConorPatrickpp/
    #desc:	Add me on google+

  - icon:	feed
    url:	/atom.xml
    desc:	Subscribe to my feed

  - icon:	key
    url:	/assets/gpgkey.txt
    desc:	GPG Key
 
    #- icon:	portfolio
    #url:	http://devpost.com/conorpp94
    #desc:	Hackathon Projects
    
menu:
  - title:	Home
    url:	/
    
    #  - title:	About
    #url:	/about.html
    
copyright:
  author:	Conor Patrick
  url:		/
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
  type_title:	Creative Commons


#twitterLink: 'https://twitter.com/_conorpp'
#mytwitter:  'By the way, I\'m now on [Twitter]({{site.twitterLink}}) too if you\'d like to follow my interests.'

